export const strings = {
  common: {
    back: 'Back',
  },
  home: {
    title: 'My Trips',
    emptyTitle: 'No trips yet',
    emptyBody: 'Create your first trip to get started.',
    createCta: 'New Trip',
    loading: 'Loading trips…',
    errorLoading: 'Could not load your trips. Please try again.',
  },
  createTrip: {
    title: 'New Trip',
    nameLabel: 'Trip name',
    namePlaceholder: 'e.g. Japan 2026',
    startLabel: 'Start date',
    endLabel: 'End date',
    destinationsLabel: 'Destination(s)',
    destinationsPlaceholder: 'e.g. Tokyo, Kyoto',
    submit: 'Create Trip',
    cancel: 'Cancel',
    errorDateRange: 'End date must be on or after the start date.',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  sections: {
    upcoming: 'Upcoming',
    past: 'Past',
  },
  status: {
    booked: 'Booked',
    to_book: 'To book',
    decide_later: 'Decide later',
  },
  reservationType: {
    stay: 'Stay',
    transport: 'Transport',
    activity: 'Activity',
  },
  reservationLegLabels: {
    stay: { start: 'Check-in', end: 'Check-out' },
    transport: { start: 'Departure', end: 'Arrival' },
    activity: { start: 'Start', end: 'End' },
  },
  reservationDetail: {
    statusLabel: 'Status',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteConfirm: 'Delete this reservation? This cannot be undone.',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add a note…',
    priceLabel: 'Price',
    noPrice: 'No price set',
    startLabel: 'Start',
    endLabel: 'End',
    mapUnavailable: 'Location not set',
    loading: 'Loading reservation…',
    errorLoading: 'Could not load this reservation.',
    notFound: 'Reservation not found.',
    errorGeneric: 'Something went wrong. Please try again.',
    nameLabel: 'Name',
    startAddressLabel: 'Start address',
    endAddressLabel: 'End address',
    geocoding: 'Locating address…',
    geocodeErrorGeneric: 'Could not locate this address. Please try again.',
  },
  stayMenu: {
    title: 'Stay',
    loading: 'Loading stays…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No stays booked yet',
    emptyBody: 'This trip has no accommodation reservations.',
    setDatesHint: 'Set trip start and end dates to see coverage gaps.',
    gapLabel: 'Not booked',
  },
} as const
