import type { TravelMode } from './travelTime'
import type { ReservationStatus } from '../types/reservation'

const travelModeVerb: Record<TravelMode, string> = {
  WALK: 'walk',
  DRIVE: 'drive',
  BICYCLE: 'by bike',
  TRANSIT: 'by transit',
  TRAIN: 'by train',
}

export const strings = {
  common: {
    back: 'Back',
    overlapBadge: '↳ Also booked during this period',
    saved: 'Saved',
  },
  appError: {
    title: 'Something went wrong.',
    body: 'Reload the page to keep going — anything you already saved is safe.',
    reload: 'Reload',
  },
  report: {
    trigger: 'Report a bug or feedback',
    menuTitle: 'What would you like to report?',
    menuBugLabel: 'Bug',
    menuFeedbackLabel: 'Feedback',
    bugFormTitle: 'Report a Bug',
    feedbackFormTitle: 'Share Feedback',
    titleLabel: 'Title',
    bugTitlePlaceholder: 'What went wrong?',
    feedbackTitlePlaceholder: 'What did you notice?',
    descriptionLabel: 'Description / steps to reproduce',
    bugDescriptionPlaceholder: 'Optional — what were you doing when it happened?',
    feedbackDescriptionLabel: 'Description',
    feedbackDescriptionPlaceholder: 'What happened, what worked or didn’t',
    typeLabel: 'Type',
    contextLabel: 'Context (optional)',
    contextPlaceholder: 'Where / with whom / situation',
    cancel: 'Cancel',
    back: 'Back',
    submit: 'Send',
    closeCta: 'Close',
    successMessage: 'Thanks — this has been logged.',
    errorMessage: 'Could not send the report. Please try again.',
  },
  home: {
    title: 'My Trips',
    emptyTitle: 'No trips yet',
    emptyBody: 'Create your first trip to get started.',
    createCta: 'New trip',
    tripLimitReached: "You've reached your plan's active trip limit.",
    loading: 'Loading trips…',
    errorLoading: 'Could not load your trips. Please try again.',
    privacyLink: 'Privacy Policy',
  },
  createTrip: {
    title: 'New Trip',
    nameLabel: 'Trip name',
    namePlaceholder: 'e.g. Peru 2026',
    startLabel: 'Start date',
    endLabel: 'End date',
    destinationsLabel: 'Destination(s)',
    destinationsPlaceholder: 'Search countries…',
    tripTypeLabel: 'Trip type (optional)',
    tripTypeUnset: 'Not specified',
    tripTypeCityTrip: 'City trip',
    tripTypeRoadTrip: 'Road trip',
    tripTypeMultiDestination: 'Multi-destination',
    tripTypeOther: 'Other',
    currencyLabel: 'Currency',
    travelerCountLabel: 'Number of travelers',
    travelerCountHint: 'Used to split shared Stay costs per person — Transport and Activities stay full price.',
    dayStartLabel: 'Day starts at',
    dayEndLabel: 'Day ends at',
    dayRangeHint: "Bounds each day's free time — adjust if you're an early riser or night owl.",
    notesLabel: 'Notes',
    notesPlaceholder: 'Trip expectations, goals, anything worth remembering…',
    submit: 'Create trip',
    cancel: 'Cancel',
    errorDateRange: 'End date must be on or after the start date.',
    errorDayRange: 'Day end time must be after day start time.',
    errorTravelerCount: 'Number of travelers must be at least 1.',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  editTrip: {
    title: 'Edit Trip',
    editCta: 'Edit trip',
    submit: 'Save changes',
  },
  deleteTrip: {
    deleteCta: 'Delete trip',
    confirmTitle: 'Delete this trip?',
    confirmMessage:
      'This will permanently delete this trip and all its reservations, notes, and reminders. This cannot be undone.',
    confirmCta: 'Delete trip',
    cancelCta: 'Cancel',
    errorGeneric: 'Could not delete this trip. Please try again.',
  },
  sections: {
    upcoming: 'Upcoming',
    past: 'Past',
  },
  status: {
    booked: 'Booked',
    to_book: 'To book',
    decide_later: 'Decide later',
  },
  reservationType: {
    stay: 'Stay',
    transport: 'Transport',
    activity: 'Activity',
  },
  reservationLegLabels: {
    stay: { start: 'Check-in', end: 'Check-out' },
    transport: { start: 'Departure', end: 'Arrival' },
    activity: { start: 'Start', end: 'End' },
  },
  reservationLegLabelsAtDisposal: { start: 'Pick-up', end: 'Drop-off' },
  reservationDetail: {
    statusLabel: 'Status',
    save: 'Save',
    delete: 'Delete',
    deleteConfirm: 'Delete this reservation? This cannot be undone.',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add a note…',
    priceLabel: 'Price',
    confirmationNumberLabel: 'Confirmation number',
    confirmationNumberPlaceholder: 'e.g. ABC123',
    currencyLabel: 'Currency',
    // TABI-211: the editable date/time fields carry the same leg wording as the read-only
    // leg rows above them (Departure/Arrival, Pick-up/Drop-off) — a generic "Start date"
    // sitting under an explicit "DEPARTURE" summary read as two unrelated things, and the
    // fields were taken for a non-editable display of the summary.
    legDateLabel: (leg: string) => `${leg} date`,
    legTimeLabel: (leg: string) => `${leg} time`,
    startLabel: 'Start',
    endLabel: 'End',
    parkingLabel: 'Parking included',
    parkingYes: 'Yes',
    parkingNo: 'No',
    checkInDeadlineLabel: 'Check-in deadline',
    checkInDateLabel: 'Check-in date',
    checkOutDateLabel: 'Check-out date',
    checkInTimeLabel: 'Check-in time',
    checkOutTimeLabel: 'Check-out time',
    startDateLabel: 'Start date',
    startTimeLabel: 'Start time',
    endDateLabel: 'End date',
    endTimeLabel: 'End time',
    defaultTimeBadge: 'Default',
    errorEndBeforeStart: 'Check-out must be after check-in.',
    errorNightsRequired: 'Number of nights is required.',
    errorDurationCrossesMidnight: "An activity can't cross midnight — reduce the duration.",
    mapUnavailable: 'Location not set',
    mapError: 'Map unavailable right now.',
    loading: 'Loading reservation…',
    errorLoading: 'Could not load this reservation.',
    notFound: 'Reservation not found.',
    errorGeneric: 'Something went wrong. Please try again.',
    nameLabel: 'Name',
    startAddressLabel: 'Start address',
    endAddressLabel: 'End address',
    startAddressLabelAtDisposal: 'Pick-up city',
    endAddressLabelAtDisposal: 'Drop-off city',
    geocoding: 'Locating address…',
    geocodeErrorGeneric: 'Could not locate this address. Please try again.',
    geocodeErrorNotFound: "We couldn't locate that address. Try a different search.",
  },
  overview: {
    title: 'Trip',
    loading: 'Loading trip…',
    errorLoading: 'Could not load this trip.',
    overviewTab: 'Overview',
    planningTab: 'Planning',
    expandMap: 'Expand map',
    needsAttentionTitle: 'Needs attention',
    needsAttentionEmpty: 'Nothing needs attention right now.',
    aiAccessRequired: "AI-assisted import isn't available on your plan.",
  },
  planning: {
    unscheduledLabel: 'Unscheduled',
    emptyTitle: 'Nothing planned yet',
    emptyBody: 'Add reservations to see your day-by-day timeline.',
    dayEmptyBody: 'Nothing planned for this day yet.',
    freeTime: (duration: string) => `${duration} free`,
    travelTime: (duration: string, mode: TravelMode) => `${duration} ${travelModeVerb[mode]}`,
    tightConnection: (shortfall: string) => `${shortfall} short on travel time`,
    longTravel: (duration: string, mode: TravelMode) => `${duration} ${travelModeVerb[mode]} — long leg`,
    longTravelDay: 'Long travel day',
    localTimeLabel: (timeZone: string) => `🕐 Local time: ${timeZone}`,
    addAtFreeTime: 'Add something here',
    dayPillStayStatus: (status: ReservationStatus) => `Stay: ${strings.status[status]}`,
    dayPillVehicleRentalStatus: (status: ReservationStatus) => `Vehicle rental: ${strings.status[status]}`,
    dayPillItemCount: (count: number) => `${count} planned item${count === 1 ? '' : 's'}`,
    tonightsStay: "Tonight's stay",
    inTransit: 'In transit',
  },
  menus: {
    overview: 'Overview',
    stay: 'Stay',
    transport: 'Transport',
    activities: 'Activities',
    budget: 'Budget',
    souvenirs: 'Souvenirs',
  },
  sidebar: {
    allTrips: 'All trips',
  },
  travelMode: {
    DRIVE: 'Drive',
    WALK: 'Walk',
    BICYCLE: 'Bike',
    TRANSIT: 'Transit',
    TRAIN: 'Train',
  },
  tripLegs: {
    title: 'Getting around',
    loading: 'Computing travel times…',
    errorLoading: 'Could not compute travel times for this trip.',
    freeTime: (duration: string) => `${duration} free before next stop`,
    tightConnection: (shortfall: string) => `Cutting it close — ${shortfall} short on travel time`,
    longTravel: (duration: string) => `${duration} travel — long leg`,
    noTransitRoute: 'Public transit unavailable for this route — check Google Maps or try another mode.',
    dismissError: 'Dismiss',
    selectMode: 'Select a travel mode to see travel time',
    addAsReservation: '+ Add reservation',
  },
  stayMenu: {
    title: 'Stay',
    loading: 'Loading stays…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No stays booked yet',
    emptyBody: 'This trip has no stay reservations.',
    setDatesHint: 'Set trip start and end dates to see coverage gaps.',
    gapLabel: 'Not booked',
    nightsCount: (nights: number) => `${nights} ${nights === 1 ? 'night' : 'nights'}`,
    addCta: 'Add reservation (Stay)',
    noParkingFlag: 'No parking',
    parkingIncludedFlag: 'Parking included',
    checkInDeadlineFlag: (time: string) => `Check-in by ${time}`,
  },
  transportMenu: {
    title: 'Transport',
    loading: 'Loading transport…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No transport booked yet',
    emptyBody: 'This trip has no flights, trains, or local transport reservations.',
    addCta: 'Add reservation (Transport)',
  },
  activitiesMenu: {
    title: 'Activities',
    loading: 'Loading activities…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No activities yet',
    emptyBody: 'This trip has no activities planned.',
    unscheduledLabel: 'Unscheduled',
    addCta: 'Add activity',
  },
  budgetMenu: {
    loading: 'Loading budget…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No prices entered yet',
    emptyBody: 'Add a price to your reservations, or add a manual category, to see your budget here.',
    totalLabel: 'Total entered so far',
    byCategoryLabel: 'By category',
    itemCount: (count: number) => `${count} ${count === 1 ? 'item' : 'items'}`,
    partialHint: (priced: number, total: number) => `${priced} of ${total} reservations have a price entered`,
    perPersonAmount: (amount: string) => `${amount}/person`,
    noPriceEntered: 'No price entered',
    manualCategoriesLabel: 'Manual categories',
    addCta: 'Add category',
    labelPlaceholder: 'e.g. Food/day, Souvenirs',
    amountPlaceholder: 'Estimated amount',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    errorGeneric: 'Could not save this category. Please try again.',
  },
  budgetCategoryDetail: {
    loading: 'Loading…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No items yet',
    emptyBody: 'Nothing in this category yet.',
    unscheduledLabel: 'Unscheduled',
  },
  budgetConverter: {
    title: 'Currency converter',
    amountPlaceholder: 'Amount',
    currencyPlaceholder: 'Currency (e.g. JPY)',
    ratePlaceholder: 'Rate',
    rateHint: (currency: string) => `1 ${currency} =`,
    resultPrefix: '=',
    incomplete: 'Enter an amount, currency, and rate.',
  },
  souvenirsMenu: {
    loading: 'Loading checklist…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No items yet',
    emptyBody: 'Add souvenirs or things to buy — check them off as you go.',
    addCta: 'Add item',
    labelPlaceholder: 'e.g. Matcha, gifts for family',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    toggleChecked: 'Toggle checked',
    errorGeneric: 'Could not save this item. Please try again.',
  },
  addReservation: {
    title: 'Add Reservation',
    typeLabel: 'Type',
    changeTypeToggle: 'Change type',
    staySubtypeLabel: 'Stay type',
    staySubtypes: {
      hotel: 'Hotel',
      camping: 'Camping',
      airbnb: 'Airbnb',
      ryokan: 'Ryokan',
      other: 'Other',
    },
    transportSubtypeLabel: 'Transport type',
    transportSubtypes: {
      point_to_point: 'Flight / Train / Bus',
      at_disposal: 'Vehicle rental',
    },
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Hotel Le Bristol Paris',
    nameAutoGeneratedPlaceholder: 'Generated from the route below',
    // TABI-203: suggested starting point for the name field, based on the chosen sub-type
    // (e.g. "New Hotel") — stays editable, never a validation requirement of its own.
    suggestedName: (subtypeLabel: string) => `New ${subtypeLabel}`,
    statusLabel: 'Status',
    startAddressLabel: 'Address',
    startAddressLabelTransport: 'Departure address',
    endAddressLabel: 'Arrival address',
    startAddressLabelAtDisposal: 'Pick-up city',
    endAddressLabelAtDisposal: 'Drop-off city',
    startLabel: 'Start',
    endLabel: 'End',
    nightsLabel: 'Nights',
    manualCheckoutToggle: 'Enter checkout date manually',
    nightsCheckoutToggle: 'Use nights instead',
    durationLabel: 'Duration',
    durationHoursLabel: 'Hours',
    durationMinutesLabel: 'Minutes',
    parkingLabel: 'Parking included',
    parkingYes: 'Yes',
    parkingNo: 'No',
    checkInDeadlineLabel: 'Check-in deadline',
    priceLabel: 'Price',
    confirmationNumberLabel: 'Confirmation number',
    confirmationNumberPlaceholder: 'e.g. ABC123',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add a note…',
    submit: 'Add reservation',
    cancel: 'Cancel',
    geocoding: 'Locating address…',
    errorNameRequired: 'Name is required.',
    errorStartRequired: 'Start date is required.',
    errorEndRequired: 'End date and time are required.',
    errorNightsRequired: 'Number of nights is required.',
    errorEndBeforeStart: 'End must be on or after start.',
    errorGeneric: 'Something went wrong. Please try again.',
    errorTripLoadFailed: "Could not load this trip's details. Please close and try again.",
    geocodeErrorGeneric: 'Could not locate this address. Please try again.',
    overlapConfirmTitle: 'Overlapping dates',
    overlapConfirmMessage: (name: string) => `This overlaps with "${name}". Is this intended?`,
    overlapNoteLabel: 'Note (optional)',
    overlapNotePlaceholder: 'Why do these overlap?',
    overlapConfirmCta: 'Yes, save anyway',
    overlapCancelCta: 'Go back',
    outOfPeriodConfirmTitle: 'Outside trip dates',
    outOfPeriodConfirmMessage: "This falls outside the trip's current dates. Extend the trip to cover it, or go back and correct the date.",
    outOfPeriodExtendCta: 'Extend trip dates',
    outOfPeriodCancelCta: 'Go back',
    locationMismatchConfirmTitle: 'Different city than planned',
    locationMismatchConfirmMessage: (reservationCity: string, plannedCity: string, dayLabel: string) =>
      `This reservation is in ${reservationCity}, but you planned ${plannedCity} for ${dayLabel}. Is that intended?`,
    locationMismatchConfirmCta: 'Yes, save anyway',
    locationMismatchCancelCta: 'Go back',
    geocodeFailureConfirmTitle: 'Address not found',
    geocodeFailureConfirmMessage: (fields: string) =>
      `We couldn't locate the ${fields} automatically. Save it as typed, without an exact map location for now?`,
    geocodeFailureConfirmCta: 'Save without location',
    geocodeFailureCancelCta: 'Go back and edit',
    extractionNoticeBanner:
      'These details were extracted automatically from your imported confirmation — please review and correct anything that’s wrong before saving.',
  },
  importConfirmation: {
    title: 'Import Confirmation Email',
    triggerLabel: 'Import confirmation',
    textLabel: 'Confirmation email or booking text',
    textPlaceholder: 'Paste the text of a booking confirmation email…',
    fileLabel: 'Or upload the email file (.eml, .txt)',
    fileErrorGeneric: 'Could not read this file. Try pasting the text instead.',
    pdfLabel: 'Or upload a PDF confirmation',
    pdfSelectedLabel: (fileName: string) => `PDF selected: ${fileName}`,
    pdfRemoveCta: 'Remove',
    pdfSizeError: 'This PDF is too large — try a smaller file, or paste the text instead.',
    photoLabel: 'Or take/upload a photo of a ticket or receipt',
    photoSelectedLabel: (fileName: string) => `Photo selected: ${fileName}`,
    photoRemoveCta: 'Remove',
    photoSizeError: 'This photo is too large — try a smaller file, or paste the text instead.',
    photoTypeError: 'Unsupported image format — try a JPEG, PNG, GIF, or WebP file.',
    urlLabel: 'Or paste a link to a confirmation page',
    urlPlaceholder: 'https://…',
    submit: 'Extract',
    cancel: 'Cancel',
    extracting: 'Reading your confirmation…',
    errorGeneric: 'Could not read this confirmation. You can enter it manually instead.',
    manualFallbackCta: 'Enter manually instead',
  },
  quickAdd: {
    title: 'Quick Add',
    triggerLabel: 'Quick add',
    textLabel: 'Describe the booking in one line',
    textPlaceholder: 'e.g. Hotel in Kyoto, Aug 10–14',
    submit: 'Create',
    cancel: 'Cancel',
    extracting: 'Reading your entry…',
    errorGeneric: 'Could not read this entry. You can enter it manually instead.',
    manualFallbackCta: 'Enter manually instead',
  },
  importPlan: {
    title: 'Import a Travel Plan',
    triggerLabel: 'Import plan',
    textLabel: 'Paste your travel plan or a planning conversation',
    textPlaceholder: 'Paste a written itinerary, an exported ChatGPT/Gemini conversation, or your own notes…',
    fileLabel: 'Or upload a text file (.txt, .eml)',
    fileErrorGeneric: 'Could not read this file. Try pasting the text instead.',
    submit: 'Extract',
    cancel: 'Cancel',
    extracting: 'Reading your plan…',
    errorGeneric: 'Could not read this plan. Check the text and try again.',
    reviewTitle: (count: number) => `Review ${count} item${count === 1 ? '' : 's'}`,
    doneCta: 'Done',
    editSaveCta: 'Edit & Save',
    discardCta: 'Discard',
    undoCta: 'Undo',
    savedChip: 'Saved',
    discardedLabel: 'Discarded',
    emptyState: "We couldn't find anything decided in this text — try pasting more detail, or enter it manually instead.",
    dateFieldLabel: 'Date',
    untitledReservation: 'Untitled reservation',
    confirmAllCta: 'Confirm all',
    confirmingProgress: (current: number, total: number) => `Confirming ${current} of ${total}…`,
    stopCta: 'Stop',
  },
  addressPicker: {
    title: 'Select an address',
    cancel: 'Cancel',
    selectionRequiredError: 'Please select an address from the list, or edit your search.',
  },
  activityPlaceSearch: {
    title: 'Find a place',
    searchLabel: 'Search',
    searchPlaceholder: 'e.g. a restaurant, museum, or landmark',
    loading: 'Searching…',
    emptyResults: 'No places found — try a different search.',
    errorGeneric: 'Could not search places. Please try again.',
    manualFallbackCta: 'Enter manually instead',
    cancel: 'Cancel',
    ratingLabel: (rating: number, count: number) => `★ ${rating.toFixed(1)} (${count})`,
  },
  nearbyPlaces: {
    title: 'Nearby places',
    loading: 'Finding nearby places…',
    emptyResults: 'No nearby places found.',
    errorGeneric: 'Could not load nearby places. Please try again.',
    addCta: 'Add',
    manualFallbackCta: 'Enter manually instead',
    cancel: 'Cancel',
    ratingLabel: (rating: number, count: number) => `★ ${rating.toFixed(1)} (${count})`,
  },
  savePlace: {
    triggerLabel: 'Save a place',
    locating: 'Finding your location…',
    saving: 'Saving…',
    locationDenied: "Couldn't access your location — search for the place instead.",
    savedMessage: 'Saved to book',
    saveErrorGeneric: 'Could not save this place. Please try again.',
  },
  dayLocation: {
    addCta: '+ Add planned location',
    label: 'Planned location',
    placeholder: 'City or area',
    save: 'Save',
    cancel: 'Cancel',
    remove: 'Remove',
    geocoding: 'Locating…',
    errorGeneric: 'Could not save this location. Please try again.',
    geocodeErrorNotFound: "We couldn't locate that address. Try a different search.",
  },
  dayNote: {
    addCta: '+ Add note',
    label: 'Note',
    placeholder: 'Add a note for this day…',
    save: 'Save',
    cancel: 'Cancel',
    remove: 'Remove',
    errorGeneric: 'Could not save this note. Please try again.',
  },
  reminders: {
    title: 'Reminders',
    addCta: '+ Add reminder',
    titlePlaceholder: 'e.g. Activate Eurail Pass',
    save: 'Save',
    cancel: 'Cancel',
    remove: 'Remove reminder',
    errorGeneric: 'Could not save this reminder. Please try again.',
  },
  privacyPolicy: {
    title: 'Privacy Policy',
    lastUpdated: 'Last updated: July 21, 2026',
    intro: [
      'This Privacy Policy explains what personal data Tabi ("Tabi", "we", "us") collects, why, and how you can control it.',
      'Tabi is developed and operated by Julian Guerrero, acting as data controller under the EU General Data Protection Regulation (GDPR). For any privacy question or request, contact jguerrero@digitaloasis.tech.',
      "Tabi is currently in early (V0.5) development. Some processes described below — such as data deletion — are handled manually rather than through in-app self-service tools, which are planned for a later release.",
    ],
    sections: [
      {
        heading: 'What data we collect',
        paragraphs: [],
        list: [
          'Account data: an anonymous session identifier created automatically the first time you open Tabi, used to associate your trips with your device/browser. This version does not require or collect an email address or password.',
          'Trip data: trip name, destination countries, start/end dates, currency, and any notes you add.',
          "Reservation data: booking type, name, price, status (Booked / To book / Decide later), notes, and — for stay, transport, and activity items — addresses, place names, geographic coordinates (latitude/longitude), and time zone, resolved via Google's Geocoding and Time Zone APIs. For stay items specifically: whether parking is included and a check-in deadline, if you enter them.",
          'Planned-location data: for days without a fixed booking, an address or area you enter, geocoded the same way.',
          'Reminders: any reminder titles and dates you create.',
        ],
      },
      {
        heading: "What we don't collect",
        paragraphs: [
          'We do not collect payment information, government ID, or biometric data, and we do not use analytics, advertising, or third-party tracking cookies.',
        ],
        list: [],
      },
      {
        heading: 'Why we collect it',
        paragraphs: [
          'We process this data solely to provide Tabi\'s core functionality: computing real travel time between your bookings, building your day-by-day timeline, detecting gaps in accommodation coverage, and surfacing reminders and "needs attention" items. We do not use your data for any other purpose.',
          'Legal basis (GDPR Art. 6): performance of the service you request when you use the app (Art. 6(1)(b)), and our legitimate interest in operating and improving Tabi (Art. 6(1)(f)).',
        ],
        list: [],
      },
      {
        heading: 'Who processes your data',
        paragraphs: [],
        list: [
          'Supabase (database & authentication) — stores your trip, reservation, and session data. Hosted in the EU (eu-west-1, Ireland).',
          'Vercel (hosting) — serves the app and runs the server-side functions that call the APIs below, via its global edge network.',
          "Google Maps Platform (Geocoding, Time Zone, Routes, and Maps JavaScript/Places Autocomplete APIs) — used to turn addresses into coordinates, compute travel time, and let you search for places. When you type or select an address, that text is sent to Google. Google's own privacy policy (https://policies.google.com/privacy) governs its processing of that data, as required by the Google Maps Platform Terms of Service.",
        ],
      },
      {
        heading: 'International data transfers',
        paragraphs: [
          'Our providers may process data outside the European Economic Area. Where they do, they rely on their own compliance frameworks (for example, Standard Contractual Clauses).',
        ],
        list: [],
      },
      {
        heading: 'Data retention',
        paragraphs: [
          'We keep your trip and reservation data for as long as your session or account exists, so you can keep using the app. If you ask us to delete your data, we remove it, normally within 30 days.',
        ],
        list: [],
      },
      {
        heading: 'Your rights',
        paragraphs: [
          'Depending on your location, you may have the right to access, correct, export, or delete your personal data, and to object to or restrict its processing. To exercise any of these rights, email jguerrero@digitaloasis.tech. You also have the right to lodge a complaint with your local data protection authority.',
        ],
        list: [],
      },
      {
        heading: 'How to delete your data',
        paragraphs: [
          'Tabi uses anonymous sessions rather than accounts in this version, so there isn\'t a self-serve "delete account" option yet. Clearing your browser\'s local storage for this site ends your local session, but your trip data remains stored until you ask us to remove it. To request deletion, email jguerrero@digitaloasis.tech — we\'ll confirm what we found and delete it, normally within 30 days.',
        ],
        list: [],
      },
      {
        heading: 'Cookies & local storage',
        paragraphs: [
          "Tabi stores a session token in your browser's local storage so you can return to your trips without signing in. We do not use analytics, advertising, or third-party tracking cookies.",
        ],
        list: [],
      },
      {
        heading: "Children's privacy",
        paragraphs: ['Tabi is not directed at children, and we do not knowingly collect data from anyone under 16.'],
        list: [],
      },
      {
        heading: 'Changes to this policy',
        paragraphs: [
          'We may update this policy as Tabi evolves — for example, when accounts and self-service deletion are added. We\'ll update the "last updated" date above whenever we do.',
        ],
        list: [],
      },
      {
        heading: 'Contact',
        paragraphs: ['Questions about this policy or your data: Julian Guerrero, jguerrero@digitaloasis.tech.'],
        list: [],
      },
    ],
  },
} as const
