export const strings = {
  common: {
    back: 'Back',
    comingSoon: 'Coming soon',
  },
  home: {
    title: 'My Trips',
    emptyTitle: 'No trips yet',
    emptyBody: 'Create your first trip to get started.',
    createCta: 'New Trip',
    loading: 'Loading trips…',
    errorLoading: 'Could not load your trips. Please try again.',
  },
  createTrip: {
    title: 'New Trip',
    nameLabel: 'Trip name',
    namePlaceholder: 'e.g. Japan 2026',
    startLabel: 'Start date',
    endLabel: 'End date',
    destinationsLabel: 'Destination(s)',
    destinationsPlaceholder: 'e.g. Tokyo, Kyoto',
    submit: 'Create Trip',
    cancel: 'Cancel',
    errorDateRange: 'End date must be on or after the start date.',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  sections: {
    upcoming: 'Upcoming',
    past: 'Past',
  },
  status: {
    booked: 'Booked',
    to_book: 'To book',
    decide_later: 'Decide later',
  },
  reservationType: {
    stay: 'Stay',
    transport: 'Transport',
    activity: 'Activity',
  },
  reservationLegLabels: {
    stay: { start: 'Check-in', end: 'Check-out' },
    transport: { start: 'Departure', end: 'Arrival' },
    activity: { start: 'Start', end: 'End' },
  },
  reservationDetail: {
    statusLabel: 'Status',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteConfirm: 'Delete this reservation? This cannot be undone.',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add a note…',
    priceLabel: 'Price',
    noPrice: 'No price set',
    startLabel: 'Start',
    endLabel: 'End',
    mapUnavailable: 'Location not set',
    loading: 'Loading reservation…',
    errorLoading: 'Could not load this reservation.',
    notFound: 'Reservation not found.',
    errorGeneric: 'Something went wrong. Please try again.',
    nameLabel: 'Name',
    startAddressLabel: 'Start address',
    endAddressLabel: 'End address',
    geocoding: 'Locating address…',
    geocodeErrorGeneric: 'Could not locate this address. Please try again.',
  },
  overview: {
    title: 'Trip',
    loading: 'Loading trip…',
    errorLoading: 'Could not load this trip.',
    overviewTab: 'Overview',
    planningTab: 'Planning',
    expandMap: 'Expand map',
    needsAttentionTitle: 'Needs attention',
    needsAttentionEmpty: 'Nothing needs attention right now.',
  },
  planning: {
    unscheduledLabel: 'Unscheduled',
    emptyTitle: 'Nothing planned yet',
    emptyBody: 'Add reservations to see your day-by-day timeline.',
    freeTime: (duration: string) => `${duration} free`,
    tightConnection: (shortfall: string) => `${shortfall} short on travel time`,
    longTravel: (duration: string) => `${duration} travel — long leg`,
    longTravelDay: 'Long travel day',
  },
  menus: {
    overview: 'Overview',
    stay: 'Stay',
    transport: 'Transport',
    activities: 'Activities',
    budget: 'Budget',
  },
  travelMode: {
    DRIVE: 'Drive',
    WALK: 'Walk',
    BICYCLE: 'Bike',
    TRANSIT: 'Transit',
    TRAIN: 'Train',
  },
  tripLegs: {
    title: 'Getting around',
    loading: 'Computing travel times…',
    errorLoading: 'Could not compute travel times for this trip.',
    freeTime: (duration: string) => `${duration} free before next stop`,
    tightConnection: (shortfall: string) => `Cutting it close — ${shortfall} short on travel time`,
    longTravel: (duration: string) => `${duration} travel — long leg`,
  },
  stayMenu: {
    title: 'Stay',
    loading: 'Loading stays…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No stays booked yet',
    emptyBody: 'This trip has no accommodation reservations.',
    setDatesHint: 'Set trip start and end dates to see coverage gaps.',
    gapLabel: 'Not booked',
    addCta: 'Add reservation',
  },
  transportMenu: {
    title: 'Transport',
    loading: 'Loading transport…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No transport booked yet',
    emptyBody: 'This trip has no flights, trains, or local transport reservations.',
    addCta: 'Add reservation',
  },
  activitiesMenu: {
    title: 'Activities',
    loading: 'Loading activities…',
    errorLoading: 'Could not load this trip.',
    emptyTitle: 'No activities yet',
    emptyBody: 'This trip has no activities planned.',
    unscheduledLabel: 'Unscheduled',
    addCta: 'Add activity',
  },
  addReservation: {
    title: 'Add Reservation',
    typeLabel: 'Type',
    types: {
      hotel: 'Hotel',
      flight: 'Flight',
      train: 'Train',
      local_transport: 'Local transport',
      activity: 'Activity',
    },
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Park Hyatt Tokyo',
    statusLabel: 'Status',
    startAddressLabel: 'Address',
    startAddressLabelTransport: 'Departure address',
    endAddressLabel: 'Arrival address',
    startLabel: 'Start',
    endLabel: 'End',
    priceLabel: 'Price',
    currencyLabel: 'Currency',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add a note…',
    submit: 'Add Reservation',
    cancel: 'Cancel',
    geocoding: 'Locating address…',
    errorNameRequired: 'Name is required.',
    errorStartRequired: 'Start date and time are required.',
    errorEndRequired: 'End date and time are required.',
    errorEndBeforeStart: 'End must be on or after start.',
    errorOverlap: (name: string) => `These dates overlap with "${name}". Adjust the dates or edit that reservation first.`,
    errorGeneric: 'Something went wrong. Please try again.',
  },
  addressPicker: {
    title: 'Select an address',
    cancel: 'Cancel',
    selectionRequiredError: 'Please select an address from the list, or edit your search.',
  },
} as const
